# Generated by Django 4.2 on 2023-09-02 23:40

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0010_alter_albums_options_alter_artists_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='my_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/sirius/homework_django_project/for_alina/music_collection/static/audio_files')), upload_to=''),
        ),
    ]
