# Generated by Django 4.2 on 2023-09-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0011_alter_artists_my_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
