# Generated by Django 4.2 on 2023-07-07 10:28

import collection_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='rating',
            field=models.IntegerField(validators=[collection_app.models.rating_validator]),
        ),
    ]
